[project]
name = "gymbuddy"
version = "0.1.0"
description = "AI Gym Buddy"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "torch",
    "numpy",
    "pyyaml",
    "wandb",
    "weave"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
